ion/urls.py
from django.conf.urls import *
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.contrib.sitemaps import Sitemap
from website.models import Page, PageCategory

class PageSitemap(Sitemap):
    changefreq = "weekly"
    priority = 0.5

    def items(self):
        lp = [page for page in Page.objects.all()]
        lpc = [pagecat for pagecat in PageCategory.objects.all()]
        return lp+lpc

    def lastmod(self, obj):
        if(type(obj) == Page):
            return obj.update_date

sitemaps = {"website":PageSitemap}

urlpatterns = [
    # Examples:
    # url(r'^$', 'ion.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    #,url(r'^polls/', include('polls.urls', namespace="polls"))
    url(r'^admin/', admin.site.urls)
    ,url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap')
    ,url(r'^', include('website.urls', namespace="website"))]

website/urls.py
from django.conf.urls import *
from django.views.generic import base
from django.views.generic.base import RedirectView
from website.feeds import LatestEntriesFeedRSS,LatestEntriesFeedAtom
from website.feeds import NewsFeedRSS,NewsFeedAtom
from website.feeds import CommentaryFeedRSS,CommentaryFeedAtom

from website import views

app_name = "ion"
urlpatterns = [
        url(r'^latest/new_pages/rss.xml?$' , LatestEntriesFeedRSS(updates=False))
        ,url(r'^latest/new_pages/atom.xml?$' , LatestEntriesFeedAtom(updates=False))
        ,url(r'^latest/updates/rss.xml?$' , LatestEntriesFeedRSS(updates=True))
        ,url(r'^latest/updates/atom.xml?$' , LatestEntriesFeedAtom(updates=True))
        ,url(r'^latest/news/rss.xml?$' , NewsFeedRSS())
        ,url(r'^latest/news/atom.xml?$' , NewsFeedAtom())
        ,url(r'^latest/commentary/rss.xml?$' , CommentaryFeedRSS())
        ,url(r'^latest/commentary/atom.xml?$' , CommentaryFeedAtom())
        ,url(r'^all_pages/index.html$' , views.allPages, name='allPages')
        ,url(r'^all_pages/?(?P<cat_path>.*).html$' , views.allPages, name='allPages')
        ,url(r'^top/news.html?$' , views.news, name='news')
        ,url(r'^top/commentary.html?$' , views.commentary, name='commentary')
        ,url(r'^about/license.html?$' , views.licenseusage, name='licenseusage')
        ,url(r'^index.html$' , views.anyPC)
        #,url(r'^favicon\.ico$', RedirectView.as_view(url='static/img/favicon.ico'))
        ,url(r'^(?P<urlString>.+)/index.html$' , views.anyPC, name='anyPC')
        ,url(r'^(?P<urlString>.+).html$' , views.anyPC, name='anyPC')
        #url(r'^(?P<category_name>.+)/(?P<page_shortname>.+)$' , views.webpage, name='webpage')
        #,url(r'^(?P<category_name>.+)$' , views.category, name='category')
        #,url(r'^(?P<category_name>.+)$' , views.category, name='category')
        ]

website/models.py
from django.db import models
from django.utils import timezone
from django.core.validators import RegexValidator, URLValidator

# Create your models here.
from mptt.models import MPTTModel, TreeForeignKey

class PageCategory(MPTTModel):
    category_name = models.CharField(max_length = 20, unique=True, validators = [RegexValidator("^[\w]+$", message="category name must be alphanumeric")])
    category_desc = models.CharField(max_length = 200)
    parent = TreeForeignKey('self', models.PROTECT, null=True, blank=True, related_name='children')
    class Meta:
        verbose_name_plural = "Page Categories"
    def __str__(self):
        return self.category_name
    def ansc_path(self):
        """return path to self separated by slashes"""
        return "/".join(a.category_name for a in self.get_ancestors(include_self=True))
    def get_absolute_url(self):
        return "/"+self.ansc_path()+"/index.html"
    def get_pages(self):
        return self.page_set.all()

class Page(models.Model):
    page_title = models.CharField(max_length = 200, help_text="Title of the page")
    page_shortname = models.CharField(max_length = 20, validators = [RegexValidator("^[\w]+$", message="shortname must be alphanumeric")], help_text="Short name of page (no special chars or spaces). This will be used for the url location of the page. Use _ to separate words.")
    page_description = models.CharField(max_length = 500, blank=True, help_text = "Description of page")
    page_text = models.TextField(blank=True, help_text="HTML content of page")
    page_category = models.ForeignKey(PageCategory, models.PROTECT)
    pub_date = models.DateTimeField('date published', help_text = "Date page was first published")
    update_date = models.DateTimeField('date updated', auto_now=True, help_text = "Date page was last updated")
    update_comment = models.CharField(max_length = 500, blank=True, help_text = "Changes made during last update")
    def __str__(self):
        return self.page_title

    def get_absolute_url(self):
        return "/"+self.page_category.ansc_path()+"/"+self.page_shortname+".html"

class NewsEntry(models.Model):
    title = models.CharField(max_length = 200, help_text="Title of the news entry")
    text = models.TextField(help_text="HTML content of page")
    pub_date = models.DateTimeField('date published', auto_now=True, help_text = "Date page was first published")
    class Meta:
        verbose_name_plural = "News Entries"
    def __str__(self):
        return self.title

class MPTTMeta:
    order_insertion_by = ['name']

class Comment(models.Model):
    link = models.URLField(blank=False, help_text="Link to commented page")
    link_title = models.CharField(max_length = 200, help_text="Title of linked page ")
    text = models.TextField(help_text="HTML comment")
    pub_date = models.DateTimeField('date published',auto_now=True, help_text = "Date comment was first published")
    def __str__(self):
        return "{0}:{1}".format(self.link_title, str(self.pub_date))

class GenericLink(models.Model):
    name =  models.CharField(max_length = 200, blank=False, help_text="Name")
    link = models.URLField(blank=False, help_text="Link")
    def __str__(self):
        return "{0}".format(self.name)


class License(GenericLink):
    pass

class LicenseUsage(models.Model):
    item = models.CharField(max_length = 200, blank=False, help_text="Name of item")
    source_name = models.CharField(max_length = 200, blank=False, help_text="Name of source")
    source_link = models.URLField(blank=False, help_text="Link to commented page")
    license = models.ForeignKey(License, models.PROTECT)
    attribution = models.TextField(help_text="HTML for attribution")
    usage = models.TextField(help_text="HTML for usage")
    notes = models.TextField(blank=True,help_text="HTML for notes")
    def __str__(self):
        return "{0}".format(self.item)

website/views.py
from django.http import Http404
from django.shortcuts import render, get_object_or_404
from website.models import PageCategory, Page, NewsEntry, Comment, LicenseUsage

# Create your views here.
def licenseusage(request) :
    cat_path = "about"
    page_shortname = "license"
    pages = Page.objects.filter(page_shortname = page_shortname)
    if len(pages) == 0 :
        raise Http404("Page with name >{0}< does not exist".format(page_shortname))
    for page in pages:
        ansc_path = page.page_category.ansc_path()
        if(cat_path == ansc_path):
            return render(request, 'website/license_usage.html',
                    {'page' : page 
                        , 'cat' : page.page_category
                        , 'licenseusages' : LicenseUsage.objects.order_by("item")
                        , 'rootCats' : get_root_cats() 
                    })
    raise Http404("Page does with name {0} not exist in path {1}".format(page_shortname,cat_path))

def commentary(request) :
    cat_path = "top"
    page_shortname = "commentary"
    pages = Page.objects.filter(page_shortname = page_shortname)
    if len(pages) == 0 :
        raise Http404("Page with name >{0}< does not exist".format(page_shortname))
    for page in pages:
        ansc_path = page.page_category.ansc_path()
        if(cat_path == ansc_path):
            return render(request, 'website/commentary.html',
                    {'page' : page 
                        , 'cat' : page.page_category
                        , 'comments' : Comment.objects.order_by("-pub_date")
                        , 'rootCats' : get_root_cats() 
                    })
    raise Http404("Page does with name {0} not exist in path {1}".format(page_shortname,cat_path))

def news(request) :
    cat_path = "top"
    page_shortname = "news"
    pages = Page.objects.filter(page_shortname = page_shortname)
    if len(pages) == 0 :
        raise Http404("Page with name >{0}< does not exist".format(page_shortname))
    for page in pages:
        ansc_path = page.page_category.ansc_path()
        if(cat_path == ansc_path):
            return render(request, 'website/news.html',
                    {'page' : page 
                        , 'cat' : page.page_category
                        , 'news_entries' : NewsEntry.objects.order_by("-pub_date")
                        , 'rootCats' : get_root_cats() 
                    })
    raise Http404("Page does with name {0} not exist in path {1}".format(page_shortname,cat_path))
def webpage(request, cat_path, page_shortname):
    pages = Page.objects.filter(page_shortname = page_shortname)
    if len(pages) == 0 :
        raise Http404("Page with name >{0}< does not exist".format(page_shortname))
    for page in pages:
        ansc_path = page.page_category.ansc_path()
        if(cat_path == ansc_path):
            return render(request, 'website/webpage.html',
                    {'page' : page 
                        , 'cat' : page.page_category
                        , 'rootCats' : get_root_cats() 
                    })
    raise Http404("Page does with name {0} not exist in path {1}".format(page_shortname,cat_path))

def category(request, cat_path):
    last_cat_name = (cat_path.split("/"))[-1]
    cats = PageCategory.objects.filter(category_name = last_cat_name)
    if len(cats) == 0:
        raise Http404("Category with name >{0}< does not exist".format(last_cat_name))
    
    cat = match_categories(cats, cat_path)
    if(cat):
        return render(request, 'website/category.html',
                {'cat' : cat 
                    , 'rootCats' : get_root_cats() 
                })
    else:
        raise Http404("Category >{0}< does not exist".format(cat_path))

def get_root_cats():
    return [i for i in PageCategory.objects.all() if i.is_root_node()]

def match_categories(cat_list, cat_path):
    for cat in cat_list:
        ansc_path = cat.ansc_path()
        if(cat_path == ansc_path):
            return cat
    return False

def allPages(request, cat_path=""):
    if(len(cat_path) == 0):
        return render(request, 'website/all_categories.html',
                {'cats' : get_root_cats()
                    , 'cat_path' : "/"
                    , 'rootCats' : get_root_cats() 
                })

    last_cat_name = (cat_path.split("/"))[-1]
    cats = PageCategory.objects.filter(category_name = last_cat_name)
    if len(cats) == 0:
        raise Http404("Category with name >{0}< does not exist".format(last_cat_name))
    
    cat = match_categories(cats, cat_path)
    if(cat):
        return render(request, 'website/all_categories.html',
                {'cats' : [cat]
                    , 'cat_path' : cat_path
                    , 'rootCats' : get_root_cats() 
                })
    else:
        raise Http404("Category >{0}< does not exist".format(cat_path))

def anyPC(request, urlString="top/home"):
    components = urlString.split("/")
    last_component = components[-1]
    if Page.objects.filter(page_shortname = last_component).count() != 0:
        sind = urlString.rfind("/")
        if sind == -1:
            return webpage(request, urlString ,urlString)
        else:
            return webpage(request, urlString[0:sind] ,components[-1])
    else:
        return category(request, urlString)

website/templates/website/all_categories.html
{% extends "website/base.html" %}
{% load mptt_tags %}

{% block pageheader %}{{cat_path}}:All Pages{% endblock %}
{% block subtitle %}{{cat_path}}:All Pages{% endblock %}
{% block content %}
{%for cat in cats %}
<h2>{{cat.ansc_path}}</h2>
<ul>
		{% for page in cat.get_pages %}
		{% if cat.is_root_node  %}
		{% with cat.ansc_path|add:"/"|add:page.page_shortname as url_path %}

		<li><a href="{% url 'website:anyPC' url_path %}">{{ page.page_title }}</a> - {{page.page_description}} <em>last updated: {{page.update_date | date:"Y-m-d Hi e"}}</em></li> 
		{% endwith %}
		{% else %}
		{% with cat.ansc_path|add:"/"|add:page.page_shortname as url_path %}
		<li><a href="{% url 'website:anyPC' url_path %}">{{ page.page_title }}</a> - {{page.page_description}} <em>last updated: {{page.update_date | date:"Y-m-d Hi e"}}</em></li> 
		{% endwith %}
		{% endif %}
		{% endfor %}
		{% with dsc=cat.get_descendants %}
		{% if cat.get_descendants|length > 0 %}
		{% recursetree dsc %}
		{% with node.ansc_path as url_path %}
		<!-- <li><a href="{% url 'website:anyPC'  url_path %}">{{node.category_desc}}</a></li> -->
		<li>{{node.category_desc}}
				{% if not node.is_leaf_node %}
				<ul class="children">
						{{ children }}
				</ul>
				{% endif %}
				{% endwith %}
				<ul>
						{% for page in node.get_pages %}
						{% if node.is_root_node  %}
						{% with node.ansc_path|add:"/"|add:page.page_shortname as url_path %}

						<li><a href="{% url 'website:anyPC' url_path %}">{{ page.page_title }}</a> - {{page.page_description}} <em>last updated: {{page.update_date | date:"Y-m-d Hi e"}}</em></li> 
						{% endwith %}
						{% else %}
						{% with node.ansc_path|add:"/"|add:page.page_shortname as url_path %}
						<li><a href="{% url 'website:anyPC' url_path %}">{{ page.page_title }}</a> - {{page.page_description}} <em>last updated: {{page.update_date | date:"Y-m-d Hi e"}}</em></li> 
						{% endwith %}
						{% endif %}
						{% endfor %}
				</ul>
				{% endrecursetree %}
		</li>
				{% endif %}
				{% endwith %}
</ul>
{% endfor %}

{% endblock %}

website/templates/website/base.html
<!DOCTYPE HTML>
{% load staticfiles %}
{% load mptt_tags %}
<html lang="en" dir="ltr">
    <head>
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<meta name="generator" content="Django 1.8.2">

        <link rel="shortcut icon" href="{% static "img/Japanese_Crest_onaga_mitu_Tomoe.ico" %}" >

        <link rel="stylesheet" type="text/css" href="{% static "css/light_with_image.css" %}" >
        <link rel="alternate stylesheet" title="Light (no image)" href="{% static "css/light_no_image.css" %}" >
        <link rel="alternate stylesheet" title="Dark" href="{% static "css/dark_with_image.css" %}" >
        <link rel="alternate stylesheet" title="Dark (no image)" href="{% static "css/dark_no_image.css" %}" >
        <!--courtesy of http://stackoverflow.com/questions/8054638/creating-a-php-header-footer  -->
        <link rel="alternate" type="application/rss+xml" title="News (RSS)" href="/latest/news/rss.xml">
        <link rel="alternate" type="application/atom+xml" title="News (Atom)" href="/latest/news/atom.xml">
        <link rel="alternate" type="application/rss+xml" title="New Pages (RSS)" href="/latest/new_pages/rss.xml">
        <link rel="alternate" type="application/atom+xml" title="New Pages (Atom)" href="/latest/new_pages/atom.xml">
        <link rel="alternate" type="application/rss+xml" title="Updates (RSS)" href="/latest/updates/rss.xml">
        <link rel="alternate" type="application/atom+xml" title="Updates (Atom)" href="/latest/updates/atom.xml">
        <link rel="alternate" type="application/rss+xml" title="Commentary (RSS)" href="/latest/commentary/rss.xml">
        <link rel="alternate" type="application/atom+xml" title="Commentary (Atom)" href="/latest/commentary/atom.xml">
        <title>Distant Constructs  - {% block pageheader %}{% endblock  %}</title>
		{% block additionalheaders %}
		{% endblock %}
    </head>
        <body>
            <header>
                <h1><a href="{% url 'website:anyPC' 'top/home' %}" title="Home Page">Distant Constructs</a></h1>
                <h2>{% block subtitle %}{% endblock  %}</h2>
            </header>
            <hr>
            <nav>
				<h2 hidden>Breadcrumbs</h2>
                <p>
                {% if not cat.is_root_node  %}
                {% for ans_cat in cat.get_ancestors %}
                {% if ans_cat.is_root_node  %}
                {% with ans_cat.category_name as url_path %}
                <a href="{%url 'website:anyPC' url_path|add:"/index"  %}">{{ ans_cat.category_name }}</a>{{">"}}
                {% endwith %}
                {% else %}
                {% with ans_cat.get_ancestors|tree_path:"/"|add:"/"|add:ans_cat.category_name as url_path %}
                <a href="{%url 'website:anyPC' url_path|add:"/index"  %}">{{ ans_cat.category_name }}</a>{{">"}}
                {% endwith %}
                {% endif %}
                {% endfor  %}
                {% endif %}
                {% block end_crumbs %}
                {{cat.category_name}}
                {% endblock %}
                </p>
            </nav>
            <hr>
            <article>
                {% block content %}
                {% endblock %}
            </article>
            <hr>
            <nav>
                <section>
				<h3 hidden>Categories</h3>
                -
                {% full_tree_for_model website.PageCategory as allCats %}
                {% for category in rootCats %}
                <a href="{% url 'website:anyPC' category.category_name|add:"/index" %}">{{ category.category_name }}</a> -
                {% endfor %}
                </section>
                <section>
				<h3 hidden>Useful Pages</h3>
				-
                <a href="{%url 'website:anyPC' "top/news"%}">news</a> -
                <a href="{%url 'website:anyPC' "top/commentary"%}">commentary</a> -
                <a href="{%url 'website:anyPC' "top/subscribe"%}">subscribe</a> -
                <a href="{%url 'website:anyPC' "top/downloads"%}">downloads</a> -
                <a href="{%url 'website:anyPC' "top/links"%}">links</a> -
                <a href="{%url 'website:anyPC' "about/license"%}">license</a> -
                <a href="{%url 'website:anyPC' "about/contact"%}">contact</a> -
                <br>
                </section>
            </nav>
            <hr>
            <footer>
                <p>
				<a href="http://validator.w3.org/check?uri=referer"> <img src="{% static "img/html5logo.svg" %}" width="31" height="31" alt="Click to Validate HTML5 (experimental)" title="HTML5 Powered (click to validate)"> </a>
				<a href="http://jigsaw.w3.org/css-validator/check/referer"> <img style="border:0;width:88px;height:31px" src="{% static "img/valid-css-v.svg" %}" alt="Click to validate CSS." /> </a>
				<a rel="license" href="https://creativecommons.org/licenses/by-sa/4.0/"><img style="border-width:0" src="{% static "img/cc-by-sa.svg" %}" width="88" height="31" alt="Creative Commons BY-SA License Logo. Click for license details."></a>
                </p>
            </footer>
        </body>
</html>

website/templates/website/category.html
{% extends "website/base.html" %}
{% load mptt_tags %}

{% block pageheader %}{{cat.category_name}} {% endblock %}
{% block additionalheaders %}
		<meta name="Description" content="{{cat.category_desc}}" />
{% endblock %}
{% block subtitle %}{{cat.category_desc}} {% endblock %}
{% block content %}
<h2 hidden>{{cat.category_desc}} Contents</h2>
<p>
<em><a href="{% url 'website:allPages' "/"|add:cat.ansc_path %}">All Pages in {{cat.category_name}} and subcategories</a></em>
</p>
<ul>
		{% for page in cat.get_pages %}
		{% if cat.is_root_node  %}
				{% with cat.ansc_path|add:"/"|add:page.page_shortname as url_path %}

				<li><a href="{% url 'website:anyPC' url_path %}">{{ page.page_title }}</a> - {{page.page_description}} <em>last updated: {{page.update_date | date:"Y-m-d Hi e"}}</em></li> 
				{% endwith %}
		{% else %}
				{% with cat.ansc_path|add:"/"|add:page.page_shortname as url_path %}
				<li><a href="{% url 'website:anyPC' url_path %}">{{ page.page_title }}</a> - {{page.page_description}} <em>last updated: {{page.update_date | date:"Y-m-d Hi e"}}</em></li> 
		{% endwith %}
		{% endif %}
		{% endfor %}
</ul>
{% with dsc=cat.get_children %}
{% if dsc|length > 0 %}
<h2>Subcategories</h2>
<ul>
		{% for node in  dsc %}
		<li>
				{% with node.ansc_path as url_path %}
				<a href="{% url 'website:anyPC'  url_path|add:"/index" %}">{{node.category_desc}}</a>
				{% if not node.is_leaf_node %}
				<ul class="children">
						{{ children }}
				</ul>
				{% endif %}
				{% endwith %}
		</li>
		{% endfor %}
</ul>
{% endif %}
{% endwith %}

{% endblock %}

website/templates/website/commentary.html
{% extends "website/base.html" %}
{% load mptt_tags %}

{% block pageheader %}{{page.page_title}} {% endblock %}
{% block additionalheaders %}
    <meta name="Description" content="{{page.page_description}}" />
{% endblock %}
{% block subtitle %}{{page.page_title}} {% endblock %}
{% block end_crumbs %}
{% if cat.is_root_node  %}
{% with cat.category_name as url_path %}
<a href="{%url 'website:anyPC' url_path  %}">{{ cat.category_name }}</a>{{">"}}
{% endwith %}
{% else %}
{% with cat.get_ancestors|tree_path:"/"|add:"/"|add:cat.category_name as url_path %}
<a href="{%url 'website:anyPC' url_path  %}">{{ cat.category_name }}</a>{{">"}}
{% endwith %}
{% endif %}
{{page.page_shortname}} 
{% endblock %}
{% block content %}
<h2 hidden>Comments</h2>
{% for comment in comments %}
<article>
		<h3><a href="{{comment.link}}">{{comment.link_title}}</a></h3>
<em>{{comment.pub_date | date:"Y-m-d Hi e"}}</em>
</article>
<br>
{{comment.text|safe}}
{% endfor %}
{% endblock %}

website/templates/website/license_usage.html
{% extends "website/base.html" %}
{% load mptt_tags %}

{% block pageheader %}{{page.page_title}} {% endblock %}
{% block additionalheaders %}
<meta name="Description" content="{{page.page_description}}" />
{% endblock %}
{% block subtitle %}{{page.page_title}} {% endblock %}
{% block end_crumbs %}
{% if cat.is_root_node  %}
{% with cat.category_name as url_path %}
<a href="{%url 'website:anyPC' url_path  %}">{{ cat.category_name }}</a>{{">"}}
{% endwith %}
{% else %}
{% with cat.get_ancestors|tree_path:"/"|add:"/"|add:cat.category_name as url_path %}
<a href="{%url 'website:anyPC' url_path  %}">{{ cat.category_name }}</a>{{">"}}
{% endwith %}
{% endif %}
{{page.page_shortname}} 
{% endblock %}
{% block content %}
		<h2>License Details</h3>
<section>
		<h3 hidden>Introduction</h3>
		<p>
		This page contains a list of media used on this site and any license exceptions
		</p>
</section>
<section>
		<h3>License</h3>
		<p>
		All content, unless otherwise noted on the <a href="#media_use">Media Use/License Exceptions table</a>, is licensed under the
		Creative Commons Attribution Share-Alike License, which is linked site-wide through the footer.
		This allows you to reuse/adapt content in any way that you want as long as you attribute it 
		and use the same license. A link to this site is sufficient attribution.
		Please refer to the <a href="https://creativecommons.org/licenses/by-sa/4.0/">official page on the Creative Commons BY-SA 4.0 license</a> for additional information.
		</p>
</section>
<section>
		<h3 id="media_use" >Media Usage and License Exemption Table</h3>
		<table>
				<tr>
						<th>Item</th>
						<th>Source</th>
						<th>License</th>
						<th>Attribution</th>
						<th>Usage</th>
						<th>Notes</th>
				</tr>
				{% for lu in licenseusages %}
				<tr>
						<td>{{lu.item}}</td>
						<td><a href="{{lu.source_link}}">{{lu.source_name}}</a></td>
						<td><a href="{{lu.license.link}}">{{lu.license.name}}</a></td>
						<td>{{lu.attribution|safe}}</td>
						<td>{{lu.usage|safe}}</td>
						<td>{{lu.notes|safe}}</td>
				</tr>
				{% endfor %}
		</table>
<section>
<br>
<em>first published: {{page.pub_date | date:"Y-m-d Hi e"}}</em>
<br>
<em>last updated: {{page.update_date | date:"Y-m-d Hi e"}}</em>
{% endblock %}

website/templates/website/news.html
{% extends "website/base.html" %}
{% load mptt_tags %}

{% block pageheader %}{{page.page_title}} {% endblock %}
{% block additionalheaders %}
    <meta name="Description" content="{{page.page_description}}" />
{% endblock %}
{% block subtitle %}{{page.page_title}} {% endblock %}
{% block end_crumbs %}
{% if cat.is_root_node  %}
{% with cat.category_name as url_path %}
<a href="{%url 'website:anyPC' url_path  %}">{{ cat.category_name }}</a>{{">"}}
{% endwith %}
{% else %}
{% with cat.get_ancestors|tree_path:"/"|add:"/"|add:cat.category_name as url_path %}
<a href="{%url 'website:anyPC' url_path  %}">{{ cat.category_name }}</a>{{">"}}
{% endwith %}
{% endif %}
{{page.page_shortname}} 
{% endblock %}
{% block content %}
<h2 hidden>News Entries</h2>
{% for news in news_entries %}
<article>
<h3>{{news.title}}</h3>
<em>{{news.pub_date | date:"Y-m-d Hi e"}}</em>
</article>
<p>
{{news.text|safe}}
</p>
{% endfor %}
{% endblock %}

website/templates/website/webpage.html
{% extends "website/base.html" %}
{% load mptt_tags %}

{% block pageheader %}{{page.page_title}} {% endblock %}
{% block additionalheaders %}
    <meta name="Description" content="{{page.page_description}}" />
{% endblock %}
{% block subtitle %}{{page.page_title}} {% endblock %}
{% block end_crumbs %}
{% if cat.is_root_node  %}
{% with cat.category_name as url_path %}
<a href="{%url 'website:anyPC' url_path|add:"/index"  %}">{{ cat.category_name }}</a>{{">"}}
{% endwith %}
{% else %}
{% with cat.get_ancestors|tree_path:"/"|add:"/"|add:cat.category_name as url_path %}
<a href="{%url 'website:anyPC' url_path|add:"/index"  %}">{{ cat.category_name }}</a>{{">"}}
{% endwith %}
{% endif %}
{{page.page_shortname}} 
{% endblock %}
{% block content %}
{{page.page_text|safe}}
<br>
<em>first published: {{page.pub_date | date:"Y-m-d Hi e"}}</em>
<br>
<em>last updated: {{page.update_date | date:"Y-m-d Hi e"}}</em>
{% endblock %}